spring.application.name: configserver

server.port: 8888

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring.cloud.app.config.server.git.uri: https://github.com/andreykolchev/microservice-app.config