discovery:
  image: cloud/discovery
  container_name: discovery
  ports:
   - "8761:8761"
gateway:
  image: cloud/api-gateway
  container_name: gateway
  ports:
   - "8080:8080"
  links:
   - discovery
hystrix:
  image: cloud/hystrix-dashboard
  container_name: hystrix-dashboard
  ports:
   - "7979:7979"
  links:
   - gateway
   - discovery