#name for service discovery
spring.application.name: back-api-sidecar
#prana port
server.port: 9999
#eureca
eureka:
  client:
   serviceUrl.defaultZone: http://localhost:8761/eureka/
   healthcheck.enabled: true

#parent port
sidecar:
  port: 8000
#  health-uri: http://localhost:8000/health


#parent checkpoint url
parent.checkpoint.url: http://localhost:${sidecar.port:}/message