spring.application.name: lifecycle

server.port: 9090

eureka:
  client.serviceUrl.defaultZone: http://discovery:8761/eureka/
  instance.preferIpAddress: true

logging.level:
        ROOT: WARN
        org.springframework.web: WARN

