spring.application.name: hystrix

endpoints:
    restart.enabled: true
    shutdown.enabled: true

server.port: 7979

eureka:
  client:
    serviceUrl.defaultZone: http://discovery:8761/eureka/
    fetchRegistry: false

logging.level:
        ROOT: WARN
        org.springframework.web: WARN