spring.application.name: gateway

server:
    port: 8080
    compression.enabled: true

endpoints:
  restart.enabled: true
  shutdown.enabled: true
  health.sensitive: false

zuul:
    ignoredServices: "*"
    routes:
        25h8_be:
            path: /25h8_be/**
            serviceId: 25h8_be
            stripPrefix: true
#        parentapi:
#            path: /back-api-sidecar/**
#            serviceId: back-api-sidecar
#            stripPrefix: true

app:
  ConnectTimeout: 100
  ReadTimeout: 3000

logging.level:
        ROOT: WARN
        org.springframework.web: WARN

eureka:
  client.serviceUrl.defaultZone: http://discovery:8761/eureka/
  instance.preferIpAddress: true